{
  "name": "Cricsheet Model",
  "id": "d03f7040-9b86-4870-a554-087d48a94ebd",
  "compatibilityLevel": 1605,
  "model": {
    "culture": "en-US",
    "collation": "Latin1_General_100_BIN2_UTF8",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "tables": [
      {
        "name": "Player",
        "lineageTag": "0256e88e-328f-4764-a135-ef906efdbfd9",
        "sourceLineageTag": "[dbo].[t_dim_player]",
        "columns": [
          {
            "name": "player_id",
            "dataType": "int64",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "player_id",
            "formatString": "0",
            "sourceProviderType": "bigint",
            "lineageTag": "e79d1e6b-b49a-4d5b-90ec-c5ef31ce8385",
            "sourceLineageTag": "player_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Player Name",
            "dataType": "string",
            "sourceColumn": "player_name",
            "sourceProviderType": "varchar",
            "lineageTag": "e0606490-3515-4e07-a704-878a52242fba",
            "sourceLineageTag": "player_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Player",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "t_dim_player",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo"
            }
          }
        ],
        "annotations": [
          {
            "name": "IsTableInBiModel",
            "value": "True"
          }
        ]
      },
      {
        "name": "Deliveries",
        "lineageTag": "d9374cd6-a1e5-4e8a-b020-3caccc840434",
        "sourceLineageTag": "[dbo].[t_fact_deliveries]",
        "columns": [
          {
            "name": "match_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "match_id",
            "formatString": "0",
            "sourceProviderType": "int",
            "lineageTag": "804765d7-a576-4df1-a7bc-5cc67dcb5ccd",
            "sourceLineageTag": "match_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "innings",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "innings",
            "formatString": "0",
            "sourceProviderType": "int",
            "lineageTag": "f3f3aa55-6bf4-4172-bb51-e78547b2a586",
            "sourceLineageTag": "innings",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "overs",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "overs",
            "formatString": "0",
            "sourceProviderType": "int",
            "lineageTag": "0f03c8e8-70c5-4fde-a677-9bcabb108308",
            "sourceLineageTag": "overs",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "balls",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "balls",
            "formatString": "0",
            "sourceProviderType": "int",
            "lineageTag": "7d6066fa-455f-487c-9adc-a2a7d1a2a9c4",
            "sourceLineageTag": "balls",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "batter_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "batter_id",
            "formatString": "0",
            "sourceProviderType": "bigint",
            "lineageTag": "cd1a13fd-eba6-495a-bb8a-9094e077654b",
            "sourceLineageTag": "batter_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "bowler_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "bowler_id",
            "formatString": "0",
            "sourceProviderType": "bigint",
            "lineageTag": "cc4ca274-cc56-490e-94c2-faca44cd170e",
            "sourceLineageTag": "bowler_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "byes",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "byes",
            "formatString": "0",
            "sourceProviderType": "int",
            "lineageTag": "966c834f-0c08-44f4-b393-0f157828d65c",
            "sourceLineageTag": "byes",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "leg_byes",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "leg_byes",
            "formatString": "0",
            "sourceProviderType": "int",
            "lineageTag": "0d3be281-e823-48ea-a2ac-8957c33b7313",
            "sourceLineageTag": "leg_byes",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "no_balls",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "no_balls",
            "formatString": "0",
            "sourceProviderType": "int",
            "lineageTag": "9486ec56-9a41-4563-a52b-a3d2f841632d",
            "sourceLineageTag": "no_balls",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "wides",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "wides",
            "formatString": "0",
            "sourceProviderType": "int",
            "lineageTag": "4fe72ac4-69e5-4b5e-9685-661201aa2dc3",
            "sourceLineageTag": "wides",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "non_striker_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "non_striker_id",
            "formatString": "0",
            "sourceProviderType": "bigint",
            "lineageTag": "202f8ab8-2628-422d-baf1-f4881a9059e6",
            "sourceLineageTag": "non_striker_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "batter_runs",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "batter_runs",
            "formatString": "0",
            "sourceProviderType": "int",
            "lineageTag": "02c2258c-f8d4-4d67-933b-0078f917aac3",
            "sourceLineageTag": "batter_runs",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "total_runs",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "total_runs",
            "formatString": "0",
            "sourceProviderType": "int",
            "lineageTag": "94aa8bb0-e036-410e-bb2a-5becb9c33b55",
            "sourceLineageTag": "total_runs",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "wicket_kind",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "wicket_kind",
            "sourceProviderType": "varchar",
            "lineageTag": "33eabbcd-931c-4aa2-b995-7a58601436d3",
            "sourceLineageTag": "wicket_kind",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "player_out_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "player_out_id",
            "formatString": "0",
            "sourceProviderType": "bigint",
            "lineageTag": "b092331a-8600-4c6b-bfe0-d83ec16c7b90",
            "sourceLineageTag": "player_out_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "fielder_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "fielder_id",
            "formatString": "0",
            "sourceProviderType": "bigint",
            "lineageTag": "6c0d094f-9303-481e-a80b-a71a428fd2b6",
            "sourceLineageTag": "fielder_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "batting_team_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "batting_team_id",
            "formatString": "0",
            "sourceProviderType": "int",
            "lineageTag": "36e4fc3f-690b-4b8d-95b8-970d555fdbd5",
            "sourceLineageTag": "match_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "match_date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "match_date",
            "formatString": "dd-MMM-yyyy",
            "sourceProviderType": "date",
            "lineageTag": "41840ad2-8d56-4410-a5ad-84a4cf099c4e",
            "sourceLineageTag": "match_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE\",\"DATECOLUMN_FORMATSTRING\"]}"
              }
            ]
          },
          {
            "name": "bowling_team_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "bowling_team_id",
            "formatString": "0",
            "sourceProviderType": "int",
            "lineageTag": "652368e7-55b4-4f9a-9ded-17936a4741c3",
            "sourceLineageTag": "match_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Deliveries",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "t_fact_deliveries",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo"
            }
          }
        ],
        "measures": [
          {
            "name": "5 Wickets #",
            "expression": [
              "",
              "CALCULATE (",
              "    COUNTROWS (",
              "        FILTER (",
              "            SUMMARIZE (",
              "                Deliveries,",
              "                Deliveries[match_id],",
              "                Deliveries[innings],",
              "                Player[Player Name]",
              "            ),",
              "            [Wickets #] >= 5",
              "        )",
              "    ),",
              "    USERELATIONSHIP ( Deliveries[bowler_id], Player[player_id] ),",
              "    USERELATIONSHIP ( Deliveries[bowling_team_id], Team[team_id] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Bowling",
            "lineageTag": "5ed66846-7561-4877-9da6-5b7dae5b7f76",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "50s #",
            "expression": [
              "",
              "COUNTROWS (",
              "    FILTER (",
              "        SUMMARIZE (",
              "            Deliveries,",
              "            Deliveries[match_id],",
              "            Deliveries[innings],",
              "            Player[Player Name]",
              "        ),",
              "        VAR _Runs = [Batter's Runs]",
              "        RETURN",
              "            _Runs >= 50",
              "                && _Runs < 100",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Batting",
            "lineageTag": "30d7046e-95c9-4d65-a324-c9c14a05302c",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Bat Innings #",
            "expression": [
              "",
              "VAR _BatInnings =",
              "    SUMMARIZE ( 'Deliveries', 'Deliveries'[match_id], 'Deliveries'[innings] )",
              "VAR _NonStrikeInnings =",
              "    CALCULATETABLE (",
              "        SUMMARIZE ( 'Deliveries', 'Deliveries'[match_id], 'Deliveries'[innings] ),",
              "        USERELATIONSHIP ( 'Deliveries'[non_striker_id], Player[player_id] )",
              "    )",
              "VAR _TotalInnings =",
              "    DISTINCT ( UNION ( _BatInnings, _NonStrikeInnings ) )",
              "RETURN",
              "    COUNTROWS ( _TotalInnings )"
            ],
            "formatString": "#,0",
            "displayFolder": "Batting",
            "lineageTag": "e7a4d100-ed07-4a6d-8f3f-5bf395bdede9",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Batter Runs or Overall",
            "expression": [
              "",
              "IF.EAGER (",
              "    ISINSCOPE ( Player[Player Name] ),",
              "    IF.EAGER (",
              "        SELECTEDVALUE ( Player[player_id] ) = -1,",
              "        CALCULATE (",
              "            [Overall Runs] - [Batter's Runs],",
              "            REMOVEFILTERS ( Player[Player Name] )",
              "        ),",
              "        [Batter's Runs]",
              "    ),",
              "    [Overall Runs]",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Batting",
            "lineageTag": "d62df7a9-087f-40b1-89dd-8375a2b6d2ed",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              },
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\"]}"
              }
            ]
          },
          {
            "name": "Batter's Runs",
            "expression": [
              "",
              "SUM ( Deliveries[batter_runs] )"
            ],
            "formatString": "#,0",
            "displayFolder": "Batting",
            "lineageTag": "45bed107-7953-4309-8cb7-b9694e6b6c18",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Batting Average",
            "expression": [
              "",
              "DIVIDE (",
              "    [Batter's Runs],",
              "    CALCULATE (",
              "        [Innings #],",
              "        USERELATIONSHIP ( Deliveries[player_out_id], Player[player_id] )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Batting",
            "lineageTag": "5f25cdbb-01f8-49d5-96b8-24b5d87e7eee",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Best Bowl Innings",
            "expression": [
              "",
              "VAR _RunsNWickets =",
              "    CALCULATETABLE (",
              "        ADDCOLUMNS (",
              "            SUMMARIZE (",
              "                Deliveries,",
              "                Deliveries[match_id],",
              "                Deliveries[innings],",
              "                Player[player_id]",
              "            ),",
              "            \"@Runs\", [Conceded Runs],",
              "            \"@Wickets\", [Wickets #]",
              "        ),",
              "        USERELATIONSHIP ( Deliveries[bowler_id], Player[player_id] ),",
              "        USERELATIONSHIP ( Deliveries[bowling_team_id], Team[team_id] )",
              "    )",
              "VAR _MaxWickets =",
              "    MAXX ( _RunsNWickets, [@Wickets] )",
              "VAR _MinRuns =",
              "    MINX ( FILTER ( _RunsNWickets, [@Wickets] = _MaxWickets ), [@Runs] )",
              "RETURN",
              "    IF ( NOT ISBLANK ( _MinRuns ), COALESCE ( _MaxWickets, 0 ) & \"/\" & _MinRuns )"
            ],
            "displayFolder": "Bowling",
            "lineageTag": "a74e8b7e-eb3b-4d23-9276-99d1a4696e06",
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"PROVIDE_FORMAT_STRING_FOR_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Bowl Innings #",
            "expression": [
              "",
              "CALCULATE (",
              "    [Innings #],",
              "    USERELATIONSHIP ( Deliveries[bowler_id], Player[player_id] ),",
              "    USERELATIONSHIP ( Deliveries[bowling_team_id], Team[team_id] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Bowling",
            "lineageTag": "e6caf2e6-3b93-4cd4-b5c6-39c781e52f69",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Bowler Overs",
            "expression": [
              "",
              "CALCULATE (",
              "    DISTINCTCOUNT ( Deliveries[overs] ),",
              "    USERELATIONSHIP ( Deliveries[bowler_id], Player[player_id] ),",
              "    USERELATIONSHIP ( Deliveries[bowling_team_id], Team[team_id] )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Bowling",
            "lineageTag": "9ea1c91d-1091-48dc-8ccb-b561694dfe88",
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Bowling Average",
            "expression": [
              "",
              "DIVIDE ( [Conceded Runs], [Wickets #] )"
            ],
            "formatString": "0.00",
            "displayFolder": "Bowling",
            "lineageTag": "26acd61d-6f01-4eef-98dc-78cd8977f2e8",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Byes Runs",
            "expression": [
              "",
              "SUM ( Deliveries[byes] )"
            ],
            "formatString": "#,0",
            "displayFolder": "Misc",
            "lineageTag": "9e5bc3ec-0cc9-48b1-a40e-0fe8cbd083f1",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Catch #",
            "expression": [
              "",
              "CALCULATE (",
              "    [Deliveries #],",
              "    USERELATIONSHIP ( Player[player_id], Deliveries[fielder_id] ),",
              "    USERELATIONSHIP ( Deliveries[bowling_team_id], Team[team_id] ),",
              "    Deliveries[wicket_kind] = \"caught\"",
              ")",
              "    + CALCULATE (",
              "        [Deliveries #],",
              "        USERELATIONSHIP ( Player[player_id], Deliveries[bowler_id] ),",
              "        USERELATIONSHIP ( Deliveries[bowling_team_id], Team[team_id] ),",
              "        Deliveries[wicket_kind] = \"caught and bowled\"",
              "    )"
            ],
            "formatString": "#,0",
            "displayFolder": "Bowling",
            "lineageTag": "774bcf00-1d61-4440-a89e-21dc4049916f",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Conceded Runs",
            "expression": [
              "",
              "CALCULATE (",
              "    [Overall Runs] - [Byes Runs] - [Leg Byes Runs],",
              "    USERELATIONSHIP ( Deliveries[bowler_id], Player[player_id] ),",
              "    USERELATIONSHIP ( Deliveries[bowling_team_id], Team[team_id] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Bowling",
            "lineageTag": "1b87e35c-1547-4a16-8353-02ec694ea274",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Cumulative Overall Runs",
            "expression": [
              "",
              "IF (",
              "    NOT ISEMPTY ( Deliveries ),",
              "    CALCULATE ( [Overall Runs], Deliveries[overs] <= MAX ( Deliveries[overs] ) )",
              ")"
            ],
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Misc",
            "lineageTag": "2f22a81e-0112-45f2-8825-0e2b1af90b31",
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Deliveries #",
            "expression": [
              "",
              "COUNTROWS ( Deliveries )"
            ],
            "formatString": "#,0",
            "displayFolder": "Misc",
            "lineageTag": "69a80e53-88d7-4b50-9330-8176eabf5518",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Did not Bat",
            "expression": [
              "",
              "VAR _StrikeBatters =",
              "    SUMMARIZE ( Deliveries, 'Player'[Player Name] )",
              "VAR _NonStrikeBatters =",
              "    CALCULATETABLE (",
              "        SUMMARIZE ( 'Deliveries', 'Player'[Player Name] ),",
              "        USERELATIONSHIP ( 'Deliveries'[non_striker_id], Player[player_id] )",
              "    )",
              "VAR _Batters =",
              "    DISTINCT ( UNION ( _StrikeBatters, _NonStrikeBatters ) )",
              "VAR _TeamBatting =",
              "    CALCULATETABLE (",
              "        VALUES ( 'Team Players'[team_id] ),",
              "        TREATAS ( _Batters, 'Player'[Player Name] )",
              "    )",
              "VAR _FullTeam =",
              "    CALCULATETABLE (",
              "        SUMMARIZE ( 'Team Players', 'Player'[Player Name] ),",
              "        _TeamBatting",
              "    )",
              "VAR _DidNotBat =",
              "    EXCEPT ( _FullTeam, _Batters )",
              "RETURN",
              "    CONCATENATEX ( _DidNotBat, 'Player'[Player Name], \", \" )"
            ],
            "isHidden": true,
            "displayFolder": "Batting",
            "lineageTag": "4451f855-4f48-4a16-8c97-448579dab0f3",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Economy",
            "expression": [
              "",
              "CALCULATE (",
              "    DIVIDE ( [Conceded Runs], ( [Deliveries #] - [Wides #] - [No Balls #] ) / 6 ),",
              "    USERELATIONSHIP ( Deliveries[bowler_id], Player[player_id] ),",
              "    USERELATIONSHIP ( Deliveries[bowling_team_id], Team[team_id] )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Bowling",
            "lineageTag": "a555f753-06c0-45fa-9546-3fd0e2b36ca4",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"USE_THE_DIVIDE_FUNCTION_FOR_DIVISION\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Extra Runs",
            "expression": [
              "",
              "[Overall Runs] - [Batter's Runs]"
            ],
            "formatString": "#,0",
            "displayFolder": "Misc",
            "lineageTag": "ba92e94a-1124-47c4-b64e-6aecb0d94e7d",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Fall of Wickets",
            "expression": [
              "",
              "VAR _OversAndBallsWithWicket =",
              "    CALCULATETABLE (",
              "        ADDCOLUMNS (",
              "            SUMMARIZE ( Deliveries, Deliveries[overs], Deliveries[balls] ),",
              "            \"@TotalBalls\",",
              "                ( Deliveries[overs] - 1 ) * 6 + Deliveries[balls]",
              "        ),",
              "        NOT ISBLANK ( Deliveries[wicket_kind] )",
              "    )",
              "VAR _AddingAttributes =",
              "    ADDCOLUMNS (",
              "        _OversAndBallsWithWicket,",
              "        \"@TotalRuns\",",
              "            VAR _CurrentBall = [@TotalBalls]",
              "            RETURN",
              "                CALCULATE (",
              "                    [Overall Runs],",
              "                    ( Deliveries[overs] - 1 ) * 6 + Deliveries[balls] <= _CurrentBall",
              "                ),",
              "        \"@WicketCount\",",
              "            VAR _CurrentBall = [@TotalBalls]",
              "            RETURN",
              "                CALCULATE (",
              "                    [Wickets #] + [Other Wickets #],",
              "                    ( Deliveries[overs] - 1 ) * 6 + Deliveries[balls] <= _CurrentBall",
              "                ),",
              "        \"@PlayerOut\",",
              "            CALCULATE (",
              "                MAXX ( Deliveries, RELATED ( 'Player'[Player Name] ) ),",
              "                USERELATIONSHIP ( Deliveries[player_out_id], 'Player'[player_id] )",
              "            ),",
              "        \"@WidesNoballs\",",
              "            VAR _CurrentOver = Deliveries[overs]",
              "            VAR _CurrentBall = Deliveries[balls]",
              "            RETURN",
              "                CALCULATE (",
              "                    [Wides #] + [No Balls #],",
              "                    Deliveries[overs] = _CurrentOver,",
              "                    Deliveries[balls] <= _CurrentBall",
              "                )",
              "    )",
              "RETURN",
              "    CONCATENATEX (",
              "        _AddingAttributes,",
              "        [@TotalRuns] & \"-\" & [@WicketCount] & \" (\" & [@PlayerOut] & \", \" & Deliveries[overs] - 1 & \".\" & Deliveries[balls] - [@WidesNoballs] & \")\",",
              "        \", \",",
              "        [@WicketCount]",
              "    )"
            ],
            "isHidden": true,
            "displayFolder": "Misc",
            "lineageTag": "fab808c3-3312-443f-9aa8-c574f7fb677d",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Final Score per Team",
            "expression": [
              "",
              "VAR _LastOver =",
              "    MAX ( Deliveries[overs] )",
              "VAR _LastBall =",
              "    MAXX ( Deliveries, ( Deliveries[overs] - 1 ) * 6 + Deliveries[balls] )",
              "        - CALCULATE ( [Wides #] + [No Balls #], Deliveries[overs] = _LastOver )",
              "VAR _OversCompleted =",
              "    QUOTIENT ( _LastBall, 6 )",
              "VAR _BallsCompleted =",
              "    MOD ( _LastBall, 6 )",
              "RETURN",
              "    [Overall Runs] & \"-\" & [Other Wickets #] + [Wickets #] + 0 & \" (\" & _OversCompleted & \".\" & _BallsCompleted & \" Ov, RR: \"",
              "        & FORMAT ( [Run Rate], \"#.00\" ) & \", Inn: \"",
              "        & SELECTEDVALUE ( 'Deliveries'[innings] ) & \")\""
            ],
            "isHidden": true,
            "displayFolder": "Misc",
            "lineageTag": "dba08fed-7979-48d2-8140-46db27b14151",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "First Ball Bowled",
            "expression": [
              "",
              "CALCULATE (",
              "    MINX ( Deliveries, ( Deliveries[overs] - 1 ) * 6 + Deliveries[balls] ),",
              "    USERELATIONSHIP ( Deliveries[bowler_id], Player[player_id] ),",
              "    USERELATIONSHIP ( Deliveries[bowling_team_id], Team[team_id] )",
              ")"
            ],
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Bowling",
            "lineageTag": "00d4cf48-2709-423a-983e-27ea0f8ff523",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "First Ball Faced",
            "expression": [
              "",
              "IF.EAGER (",
              "    SELECTEDVALUE ( Player[player_id] ) = -1,",
              "    999,",
              "    MINX ( Deliveries, ( Deliveries[overs] - 1 ) * 6 + Deliveries[balls] )",
              ")"
            ],
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Misc",
            "lineageTag": "297ed745-0a72-4aa8-a3bf-54bb649a8308",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Fours #",
            "expression": [
              "",
              "CALCULATE ( [Deliveries #], Deliveries[batter_runs] = 4 )"
            ],
            "formatString": "#,0",
            "displayFolder": "Batting",
            "lineageTag": "ac8a80f1-4cbc-43a5-80e4-5048ac18e669",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Highest Score",
            "expression": [
              "",
              "MAXX (",
              "    SUMMARIZE ( Deliveries, Deliveries[match_id], Deliveries[innings] ),",
              "    [Batter's Runs]",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Batting",
            "lineageTag": "625d236c-eb61-43dc-bec7-07be12b0bf84",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Last Played Date",
            "expression": [
              "",
              "MAX ( 'Team Players'[match_date] )"
            ],
            "formatString": "dd-MMM-yyyy",
            "displayFolder": "Misc",
            "lineageTag": "7fc2ed13-c223-44c5-a263-8bb7d7c62366",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              },
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Leg Byes Runs",
            "expression": [
              "",
              "SUM ( Deliveries[leg_byes] )"
            ],
            "formatString": "#,0",
            "displayFolder": "Misc",
            "lineageTag": "d5f4b081-cb82-4332-ae40-aa5c29c0bb1d",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Maiden #",
            "expression": [
              "",
              "CALCULATE (",
              "    VAR _RunsPerOver =",
              "        ADDCOLUMNS (",
              "            SUMMARIZE (",
              "                Deliveries,",
              "                Deliveries[match_id],",
              "                Deliveries[innings],",
              "                Player[Player Name],",
              "                Deliveries[overs]",
              "            ),",
              "            \"@Runs\", [Overall Runs]",
              "        )",
              "    VAR _NoRunsPerOver =",
              "        FILTER ( _RunsPerOver, [@Runs] = 0 )",
              "    RETURN",
              "        COUNTROWS ( _NoRunsPerOver ),",
              "    USERELATIONSHIP ( Deliveries[bowler_id], Player[player_id] ),",
              "    USERELATIONSHIP ( Deliveries[bowling_team_id], Team[team_id] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Bowling",
            "lineageTag": "27a07d42-b520-4438-98b7-531afb21f89b",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Match #",
            "expression": [
              "",
              "DISTINCTCOUNT ( 'Team Players'[match_id] )"
            ],
            "formatString": "#,0",
            "displayFolder": "Misc",
            "lineageTag": "6cd22ded-cb6e-4570-a701-27048ab4acf4",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Match Wins #",
            "expression": [
              "",
              "CALCULATE (",
              "    [Match #],",
              "    'Team Players'[match_winner_id] = 'Team Players'[team_id]",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Misc",
            "lineageTag": "0815f23f-5ad7-4acf-a783-45c5858a8d0f",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Max Runs Per Over",
            "expression": [
              "",
              "CALCULATE (",
              "    MAXX (",
              "        SUMMARIZE (",
              "            Deliveries,",
              "            'Deliveries'[match_id],",
              "            Deliveries[innings],",
              "            Deliveries[overs]",
              "        ),",
              "        [Overall Runs]",
              "    ),",
              "    REMOVEFILTERS ( Deliveries[innings] ),",
              "    ALLSELECTED ()",
              ")"
            ],
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Misc",
            "lineageTag": "b79848e4-1eee-43fe-8731-0b814fab21fd",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "No Balls #",
            "expression": [
              "",
              "CALCULATE ( [Deliveries #], Deliveries[no_balls] <> 0 )"
            ],
            "formatString": "#,0",
            "displayFolder": "Misc",
            "lineageTag": "52b21d7d-673a-4171-a397-08ffe70228fe",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "No Balls Bowled #",
            "expression": [
              "",
              "CALCULATE (",
              "    [No Balls #],",
              "    USERELATIONSHIP ( Deliveries[bowler_id], Player[player_id] ),",
              "    USERELATIONSHIP ( Deliveries[bowling_team_id], Team[team_id] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Bowling",
            "lineageTag": "b789f9a9-5533-4550-bd63-95676e51a551",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Not Outs #",
            "expression": [
              "",
              "VAR _MatchOuts =",
              "    CALCULATE (",
              "        [Innings #],",
              "        USERELATIONSHIP ( Deliveries[player_out_id], 'Player'[player_id] )",
              "    )",
              "VAR _MatchBatted = [Bat Innings #]",
              "RETURN",
              "    _MatchBatted - _MatchOuts"
            ],
            "formatString": "#,0",
            "displayFolder": "Batting",
            "lineageTag": "9266542b-375d-4963-ad3d-47eff6a24d20"
          },
          {
            "name": "Other Wickets #",
            "expression": [
              "",
              "CALCULATE (",
              "    [Deliveries #],",
              "    USERELATIONSHIP ( Deliveries[bowler_id], Player[player_id] ),",
              "    USERELATIONSHIP ( Deliveries[bowling_team_id], Team[team_id] ),",
              "    Deliveries[wicket_kind]",
              "        IN { \"obstructing the field\", \"run out\" }",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Bowling",
            "lineageTag": "606b8104-ab7a-407a-87aa-2974c2ada0c0",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Over #",
            "expression": [
              "",
              "COUNTROWS (",
              "    SUMMARIZE (",
              "        Deliveries,",
              "        Deliveries[match_id],",
              "        'Deliveries'[innings],",
              "        Deliveries[overs]",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Misc",
            "lineageTag": "445e2591-8a91-4f4a-9b8d-d16297054b65"
          },
          {
            "name": "Overall Runs",
            "expression": [
              "",
              "SUM ( Deliveries[total_runs] )"
            ],
            "formatString": "#,0",
            "displayFolder": "Misc",
            "lineageTag": "509c063a-36c7-4fcd-bd2a-be3774aa4d5f",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Player of Match #",
            "expression": [
              "",
              "CALCULATE (",
              "    [Match #],",
              "    USERELATIONSHIP ( 'Team Players'[player_of_match_id], Player[player_id] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Misc",
            "lineageTag": "4b9afb6c-c585-43d9-89fd-9aade0866d01",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Run Rate",
            "expression": [
              "",
              "CALCULATE (",
              "    DIVIDE ( [Overall Runs], [Over #] ),",
              "    Deliveries[overs] <= MAX ( Deliveries[overs] )",
              ")"
            ],
            "formatString": "#.00",
            "displayFolder": "Misc",
            "lineageTag": "5c49639f-31da-4b31-a39d-16ee9c8b12a3",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              },
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Runs Color",
            "expression": [
              "",
              "IF (",
              "    NOT ISBLANK ( MAX ( Deliveries[wicket_kind] ) ),",
              "    \"#E66C37\",",
              "    SWITCH (",
              "        [Overall Runs],",
              "        0, \"#CCCCCC\",",
              "        1, \"#B9DBFB\",",
              "        2, \"#A0D1FF\",",
              "        3, \"#70BBFF\",",
              "        4, \"#41A4FF\",",
              "        5, \"#0D6ABF\",",
              "        6, \"#094780\"",
              "    )",
              ")"
            ],
            "isHidden": true,
            "displayFolder": "Misc",
            "lineageTag": "5c4cf95d-dabc-4401-82f5-9cf88c91e0d2",
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Season #",
            "expression": [
              "",
              "COUNTROWS ( SUMMARIZE ( 'Team Players', 'Match'[Season] ) )"
            ],
            "formatString": "#,0",
            "displayFolder": "Misc",
            "lineageTag": "0fc6172d-1ecf-4366-8b64-2ef581fb84e9",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Season Wins #",
            "expression": [
              "",
              "VAR _LastMatchOfSeason =",
              "    CALCULATETABLE (",
              "        ADDCOLUMNS (",
              "            SUMMARIZE ( 'Team Players', 'Match'[Season] ),",
              "            \"@LastMatchOfSeason\", CALCULATE ( MAX ( Match[match_id] ) )",
              "        ),",
              "        REMOVEFILTERS ( Team ),",
              "        REMOVEFILTERS ( Player )",
              "    )",
              "VAR _LineageEnabled =",
              "    TREATAS ( _LastMatchOfSeason, Match[Season], Match[match_id] )",
              "RETURN",
              "    CALCULATE (",
              "        [Season #],",
              "        KEEPFILTERS ( _LineageEnabled ),",
              "        'Team Players'[match_winner_id] = 'Team Players'[team_id]",
              "    )"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Misc",
            "lineageTag": "47b74d9b-58c2-485d-976f-69ccf7ec9947",
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\"]}"
              }
            ]
          },
          {
            "name": "Sixes #",
            "expression": [
              "",
              "CALCULATE ( [Deliveries #], Deliveries[batter_runs] = 6 )"
            ],
            "formatString": "#,0",
            "displayFolder": "Batting",
            "lineageTag": "6ef78f1b-d99b-4a15-bb98-c7a5c361a1bb",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Strike Rate",
            "expression": [
              "",
              "DIVIDE ( [Batter's Runs] * 100, [Deliveries #] - [Wides #] )"
            ],
            "formatString": "0.00",
            "displayFolder": "Batting",
            "lineageTag": "5d610a0a-5239-44c1-86d4-f2f1a21f90ec",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Total Balls per Over",
            "expression": [
              "",
              "CALCULATE (",
              "    MAX ( Deliveries[balls] ),",
              "    REMOVEFILTERS ( Deliveries[innings], Deliveries[overs], Deliveries[balls] )",
              ")"
            ],
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Misc",
            "lineageTag": "a2bccab0-7597-46b3-a6df-7c5060563c58",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Total Overs",
            "expression": [
              "",
              "SWITCH (",
              "    MAX ( Match[Match Type] ),",
              "    \"T20\", 20,",
              "    \"ODI\", 50,",
              "    CALCULATE (",
              "        MAX ( Deliveries[overs] ),",
              "        REMOVEFILTERS ( Deliveries[overs], Deliveries[innings] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Misc",
            "lineageTag": "6d1bc84a-2cfe-4996-aa1a-91440241837c",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Wicket Details",
            "expression": [
              "",
              "VAR _outPlayer = [Player Out Name]",
              "RETURN",
              "    IF ( NOT ISBLANK ( _outPlayer ), _outPlayer & \" - \" & [Wicket Status] )"
            ],
            "isHidden": true,
            "displayFolder": "Misc",
            "lineageTag": "36002050-3064-4f3e-9268-de28cdda7a73",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Wicket Status",
            "expression": [
              "",
              "VAR _hasValue =",
              "    NOT ISEMPTY ( Deliveries )",
              "        || CALCULATE (",
              "            NOT ISEMPTY ( Deliveries ),",
              "            USERELATIONSHIP ( 'Deliveries'[non_striker_id], Player[player_id] )",
              "        )",
              "RETURN",
              "    CALCULATE (",
              "        VAR _WicketKind =",
              "            MAX ( Deliveries[wicket_kind] )",
              "        VAR _Bowler =",
              "            CALCULATE (",
              "                MAX ( Player[Player Name] ),",
              "                REMOVEFILTERS ( Player ),",
              "                Player[player_id] = MAX ( 'Deliveries'[bowler_id] )",
              "            )",
              "        VAR _Fielder =",
              "            CALCULATE (",
              "                MAX ( Player[Player Name] ),",
              "                REMOVEFILTERS ( Player ),",
              "                Player[player_id] = MAX ( 'Deliveries'[fielder_id] )",
              "            )",
              "        RETURN",
              "            IF (",
              "                ISINSCOPE ( Player[Player Name] ) || ISINSCOPE ( Deliveries[overs] ),",
              "                COALESCE (",
              "                    SWITCH (",
              "                        _WicketKind,",
              "                        \"caught\",",
              "                            \"c \" & _Fielder & \" b \" & _Bowler,",
              "                        \"caught and bowled\", \"c & b \" & _Bowler,",
              "                        \"run out\",",
              "                            \"run out (\" & _Fielder & \")\",",
              "                        \"bowled\", \"b \" & _Bowler,",
              "                        \"stumped\",",
              "                            \"st \" & _Fielder & \" b \" & _Bowler,",
              "                        \"lbw\", \"lbw b \" & _Bowler,",
              "                        \"hit wicket\", \"hit wkt b \" & _Bowler,",
              "                        _WicketKind",
              "                    ),",
              "                    IF ( _hasValue, \"not out\" )",
              "                )",
              "            ),",
              "        USERELATIONSHIP ( Deliveries[player_out_id], Player[player_id] )",
              "    )"
            ],
            "isHidden": true,
            "displayFolder": "Misc",
            "lineageTag": "92ec9886-2d80-4d8a-a77c-31542dff386c",
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Wickets #",
            "expression": [
              "",
              "CALCULATE (",
              "    [Wickets # of Batting Team],",
              "    USERELATIONSHIP ( Deliveries[bowling_team_id], Team[team_id] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Bowling",
            "lineageTag": "942a249b-3783-4635-87dd-c74abf334602"
          },
          {
            "name": "Wides #",
            "expression": [
              "",
              "CALCULATE ( [Deliveries #], Deliveries[wides] <> 0 )"
            ],
            "formatString": "#,0",
            "displayFolder": "Misc",
            "lineageTag": "7edde242-0d7e-458e-865d-dbee5183c7b7",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Wides Bowled #",
            "expression": [
              "",
              "CALCULATE (",
              "    [Wides #],",
              "    USERELATIONSHIP ( Deliveries[bowler_id], Player[player_id] ),",
              "    USERELATIONSHIP ( Deliveries[bowling_team_id], Team[team_id] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Bowling",
            "lineageTag": "dafcdbb3-f2ac-4e24-a41c-919c88fa1055",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Win Ratio",
            "expression": [
              "",
              "DIVIDE ( [Match Wins #], [Match #] )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Misc",
            "lineageTag": "d24d1922-487a-4bab-b91a-c96864a7b553",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"PERCENTAGE_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Year Span",
            "expression": [
              "",
              "VAR _MinYear =",
              "    YEAR ( MIN ( 'Team Players'[match_date] ) )",
              "VAR _MaxYear =",
              "    YEAR ( MAX ( 'Team Players'[match_date] ) )",
              "RETURN",
              "    IF ( NOT ISBLANK ( _MaxYear ), _MinYear & \"-\" & _MaxYear )"
            ],
            "displayFolder": "Misc",
            "lineageTag": "b7e9aaa0-2549-450f-84b9-ecfb81d23f5a",
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"PROVIDE_FORMAT_STRING_FOR_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "100s #",
            "expression": [
              "",
              "COUNTROWS (",
              "    FILTER (",
              "        SUMMARIZE (",
              "            Deliveries,",
              "            Deliveries[match_id],",
              "            Deliveries[innings],",
              "            Player[Player Name]",
              "        ),",
              "        [Batter's Runs] >= 100",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Batting",
            "lineageTag": "8eece48e-e217-4bc3-840e-e0cbc25afa37",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Innings #",
            "expression": [
              "",
              "COUNTROWS (",
              "    SUMMARIZE ( 'Deliveries', 'Deliveries'[match_id], 'Deliveries'[innings] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Misc",
            "lineageTag": "a1323a71-9d0a-4ff4-a8b1-c2a5178b4d4c"
          },
          {
            "name": "Batting Team with Score",
            "expression": [
              "",
              "IF (",
              "    NOT ISEMPTY ( 'Deliveries' ),",
              "    MAXX ( Deliveries, RELATED ( 'Team'[Team] ) ) & \": \" & [Final Score per Team]",
              ")"
            ],
            "isHidden": true,
            "displayFolder": "Batting",
            "lineageTag": "e6821455-0842-45d6-8cbb-fa0376274e14",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Bowler Name",
            "expression": [
              "",
              "CALCULATE (",
              "    MAXX ( 'Deliveries', RELATED ( 'Player'[Player Name] ) ),",
              "    USERELATIONSHIP ( Deliveries[bowler_id], Player[player_id] ),",
              "    USERELATIONSHIP ( Deliveries[bowling_team_id], Team[team_id] )",
              ")"
            ],
            "isHidden": true,
            "displayFolder": "Bowling",
            "lineageTag": "a4655852-6fc8-40f6-a951-f082dcfe0497",
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Batsman Name",
            "expression": [
              "",
              "MAXX ( 'Deliveries', RELATED ( 'Player'[Player Name] ) )"
            ],
            "isHidden": true,
            "displayFolder": "Batting",
            "lineageTag": "c6d7adb0-0ce6-40d0-a405-2c644aad5930",
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Player Out Name",
            "expression": [
              "",
              "CALCULATE (",
              "    MAXX ( 'Deliveries', RELATED ( 'Player'[Player Name] ) ),",
              "    USERELATIONSHIP ( 'Deliveries'[player_out_id], 'Player'[player_id] )",
              ")"
            ],
            "isHidden": true,
            "displayFolder": "Batting",
            "lineageTag": "272411e4-5d4f-4e2b-a4b4-3bce03bb7fb5",
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Cumulative Wickets Score",
            "expression": [
              "",
              "IF (",
              "    NOT ISBLANK ( MAX ( Deliveries[wicket_kind] ) ),",
              "    [Cumulative Overall Runs]",
              ")"
            ],
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Misc",
            "lineageTag": "ec4a8bc5-33c3-4d21-a3b1-4db977b0dedf",
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Cumulative Wickets",
            "expression": [
              "",
              "IF (",
              "    NOT ISEMPTY ( Deliveries ),",
              "    CALCULATE (",
              "        [Wickets # of Batting Team],",
              "        Deliveries[overs] <= MAX ( Deliveries[overs] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Misc",
            "lineageTag": "e50df5b7-c0ad-49ed-8a71-0ce1b1c2f4e5",
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Final Score",
            "expression": [
              "",
              "CONCATENATEX (",
              "    SUMMARIZE ( 'Deliveries', 'Deliveries'[innings], 'Team'[Team] ),",
              "    VAR _BattingTeam = 'Team'[Team]",
              "    VAR _ScoreBattingTeam = [Overall Runs]",
              "    VAR _WicketsOfBattingTeam =",
              "        CALCULATE ( [Deliveries #], NOT ISBLANK ( Deliveries[wicket_kind] ) )",
              "    RETURN",
              "        _BattingTeam & \": \" & _ScoreBattingTeam & \"-\"",
              "            & COALESCE ( _WicketsOfBattingTeam, 0 ),",
              "    UNICHAR ( 10 ),",
              "    'Deliveries'[innings]",
              ")"
            ],
            "isHidden": true,
            "displayFolder": "Misc",
            "lineageTag": "b044a995-d15b-4e71-a1a2-a0e5016af2a5",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Matches won Fielding First #",
            "expression": [
              "",
              "CALCULATE (",
              "    [Match #],",
              "    'Team Players'[match_winner_id] = 'Team Players'[team_id]",
              "        && 'Team Players'[first_field_id] = 'Team Players'[team_id]",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Bowling",
            "lineageTag": "e73f72a4-4160-451b-bc41-77c52ba10b08",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Matches won Batting First #",
            "expression": [
              "",
              "CALCULATE (",
              "    [Match #],",
              "    'Team Players'[match_winner_id] = 'Team Players'[team_id]",
              "        && 'Team Players'[first_bat_id] = 'Team Players'[team_id]",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Batting",
            "lineageTag": "64290324-5b50-476c-a7e7-edfdb7026044",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Wickets # of Batting Team",
            "expression": [
              "",
              "CALCULATE (",
              "    [Deliveries #],",
              "    USERELATIONSHIP ( Deliveries[bowler_id], Player[player_id] ),",
              "    Deliveries[wicket_kind]",
              "        IN { \"bowled\", \"caught\", \"caught and bowled\", \"lbw\", \"stumped\", \"hit wicket\" }",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Misc",
            "lineageTag": "bea9b4e9-7299-447d-8a91-b68f602cd65d"
          }
        ],
        "annotations": [
          {
            "name": "IsTableInBiModel",
            "value": "True"
          }
        ]
      },
      {
        "name": "Match",
        "lineageTag": "bbec02f0-5ade-4f81-a8a2-f43136658d60",
        "sourceLineageTag": "[dbo].[t_dim_match]",
        "columns": [
          {
            "name": "match_id",
            "dataType": "int64",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "match_id",
            "formatString": "0",
            "sourceProviderType": "int",
            "lineageTag": "b15258c9-a38a-4652-bc0a-58df67e2d35a",
            "sourceLineageTag": "match_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Match Gender",
            "dataType": "string",
            "sourceColumn": "match_gender",
            "sourceProviderType": "varchar",
            "lineageTag": "e9501c1d-e767-4954-9379-684fb48e7c18",
            "sourceLineageTag": "match_gender",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Season",
            "dataType": "string",
            "sourceColumn": "season",
            "sourceProviderType": "varchar",
            "lineageTag": "6f6d6f1c-ce6e-49df-aabb-44c331a6ccef",
            "sourceLineageTag": "season",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Event Name",
            "dataType": "string",
            "sourceColumn": "event_name",
            "sourceProviderType": "varchar",
            "lineageTag": "e8e16d6e-2e6a-4ed1-aa9b-d974341bdf61",
            "sourceLineageTag": "event_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Event Match Number",
            "dataType": "int64",
            "sourceColumn": "event_match_number",
            "formatString": "0",
            "sourceProviderType": "int",
            "lineageTag": "cfc9b119-c43f-46d9-a588-6c040600e4ad",
            "sourceLineageTag": "event_match_number",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "city",
            "sourceProviderType": "varchar",
            "lineageTag": "0c4d11df-7a80-4a9f-9b58-87064bf07ba8",
            "sourceLineageTag": "city",
            "dataCategory": "City",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Venue",
            "dataType": "string",
            "sourceColumn": "venue",
            "sourceProviderType": "varchar",
            "lineageTag": "1e9129ac-f3aa-4e1a-a01a-c553b262d947",
            "sourceLineageTag": "venue",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Match Type",
            "dataType": "string",
            "sourceColumn": "match_type",
            "sourceProviderType": "varchar",
            "lineageTag": "cefc9e9a-305b-422a-8220-71a1b15eae1c",
            "sourceLineageTag": "match_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Toss Decision",
            "dataType": "string",
            "sourceColumn": "toss_decision",
            "sourceProviderType": "varchar",
            "lineageTag": "b3dd9893-4496-45b6-8a13-c0c05808019d",
            "sourceLineageTag": "toss_decision",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Match Result",
            "dataType": "string",
            "sourceColumn": "match_result",
            "sourceProviderType": "varchar",
            "lineageTag": "22f33c12-b1aa-4e93-9c55-4b1f53807c2a",
            "sourceLineageTag": "match_result",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Team Type",
            "dataType": "string",
            "sourceColumn": "team_type",
            "sourceProviderType": "varchar",
            "lineageTag": "57715c67-9d16-4f07-a844-e9990b741936",
            "sourceLineageTag": "team_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Event Group",
            "dataType": "string",
            "sourceColumn": "event_group",
            "sourceProviderType": "varchar",
            "lineageTag": "66d43bd9-6a1c-4ff6-baeb-aa21b3ee0706",
            "sourceLineageTag": "event_group",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Match Result Method",
            "dataType": "string",
            "sourceColumn": "match_result_method",
            "sourceProviderType": "varchar",
            "lineageTag": "a38721b4-d996-45ca-9a27-76411ab1e148",
            "sourceLineageTag": "match_result_method",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Umpires",
            "dataType": "string",
            "sourceColumn": "umpires",
            "sourceProviderType": "varchar",
            "lineageTag": "ad850f5e-3536-4db9-85ac-d80688cf336f",
            "sourceLineageTag": "umpires",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Match Won by Runs",
            "dataType": "string",
            "sourceColumn": "match_won_by_runs",
            "sourceProviderType": "varchar",
            "lineageTag": "83ef820e-6b1e-4b84-915a-caa25e3327e9",
            "sourceLineageTag": "match_result",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Match Won by Wickets",
            "dataType": "string",
            "sourceColumn": "match_won_by_wickets",
            "sourceProviderType": "varchar",
            "lineageTag": "9aa74d1f-9866-4b32-82cd-bc5d8fb9ccd9",
            "sourceLineageTag": "match_result",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Match Won by Innings",
            "dataType": "string",
            "sourceColumn": "match_won_by_innings",
            "sourceProviderType": "varchar",
            "lineageTag": "d3fd9099-c52c-46a1-8a62-bb14dbbf62b5",
            "sourceLineageTag": "match_result",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Match",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "t_dim_match",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo"
            }
          }
        ],
        "annotations": [
          {
            "name": "IsTableInBiModel",
            "value": "True"
          }
        ]
      },
      {
        "name": "Team Players",
        "lineageTag": "e8305a30-4cd9-4ef2-a01e-5b2d59eb3914",
        "sourceLineageTag": "[dbo].[t_fact_team_players]",
        "columns": [
          {
            "name": "match_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "match_id",
            "formatString": "0",
            "sourceProviderType": "int",
            "lineageTag": "39b4dd5e-b8ac-41a0-8d21-740c7c2d7600",
            "sourceLineageTag": "match_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "team_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "team_id",
            "formatString": "0",
            "sourceProviderType": "bigint",
            "lineageTag": "2e7e5362-e4f2-4366-928f-f0d7a22a78fb",
            "sourceLineageTag": "team_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "player_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "player_id",
            "formatString": "0",
            "sourceProviderType": "bigint",
            "lineageTag": "f24f59ef-d8ab-45dc-80a1-0451713e11f7",
            "sourceLineageTag": "player_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "match_winner_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "match_winner_id",
            "formatString": "0",
            "sourceProviderType": "bigint",
            "lineageTag": "1f76300e-6af1-4075-84aa-c2d4f4f9f59b",
            "sourceLineageTag": "match_winner_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "player_of_match_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "player_of_match_id",
            "formatString": "0",
            "sourceProviderType": "bigint",
            "lineageTag": "cff41bed-de62-4a77-83a1-45273d093ea9",
            "sourceLineageTag": "player_of_match_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "toss_winner_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "toss_winner_id",
            "formatString": "0",
            "sourceProviderType": "bigint",
            "lineageTag": "fce8bfe5-372f-4446-a594-410e1cfc5b81",
            "sourceLineageTag": "toss_winner_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "first_bat_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "first_bat_id",
            "formatString": "0",
            "sourceProviderType": "bigint",
            "lineageTag": "284e45f1-7c97-4af5-9d2f-a84837007a65",
            "sourceLineageTag": "first_bat_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "first_field_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "first_field_id",
            "formatString": "0",
            "sourceProviderType": "bigint",
            "lineageTag": "7e61578f-85d8-4ffe-b8bd-d4d0129fee40",
            "sourceLineageTag": "first_field_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "match_date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "match_date",
            "formatString": "dd-MMM-yyyy",
            "sourceProviderType": "date",
            "lineageTag": "0e91285a-8a2e-4823-b4b7-330dea4ca71b",
            "sourceLineageTag": "match_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE\",\"DATECOLUMN_FORMATSTRING\"]}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Team Players",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "t_fact_team_players",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo"
            }
          }
        ],
        "measures": [
          {
            "name": "Match Result",
            "expression": [
              "",
              "IF (",
              "    NOT ISEMPTY ( 'Team Players' ),",
              "    CALCULATE (",
              "        VAR _MatchResult =",
              "            MAX ( 'Match'[Match Result] )",
              "        VAR _MatchWinner =",
              "            CALCULATE (",
              "                MAXX ( 'Team Players', RELATED ( 'Team'[Team] ) ),",
              "                USERELATIONSHIP ( 'Team Players'[match_winner_id], 'Team'[team_id] )",
              "            )",
              "        VAR _MatchResultWinner =",
              "            IF (",
              "                NOT ISBLANK ( _MatchResult ) && NOT ISBLANK ( _MatchWinner ),",
              "                \" (\" & _MatchWinner & \" won)\"",
              "            )",
              "        VAR _WonByRuns =",
              "            MAX ( 'Match'[Match Won by Runs] )",
              "        VAR _WonByWickets =",
              "            MAX ( 'Match'[Match Won by Wickets] )",
              "        VAR _WonByInnings =",
              "            MAX ( 'Match'[Match Won by Innings] )",
              "        VAR _WinMethod =",
              "            MAX ( 'Match'[Match Result Method] )",
              "        VAR _RunsOrWickets =",
              "            IF ( ISBLANK ( _WonByRuns ), \" wickets\", \" runs\" )",
              "        VAR _Result =",
              "            _MatchWinner & \" won by \"",
              "                & COALESCE ( _WonByRuns, _WonByWickets ) & _RunsOrWickets",
              "                & IF ( NOT ISBLANK ( _WonByInnings ), \" and \" & _WonByInnings & \" innings\" )",
              "        RETURN",
              "            COALESCE ( _MatchResult & _MatchResultWinner, _Result )",
              "                & IF ( NOT ISBLANK ( _WinMethod ), \" (\" & _WinMethod & \")\" )",
              "    )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "e2b4345d-0600-431a-ba4b-146f2e967839",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Teams Played",
            "expression": [
              "",
              "CONCATENATEX (",
              "    SUMMARIZE ( 'Team Players', 'Team'[Team] ),",
              "    'Team'[Team],",
              "    UNICHAR ( 10 ) & \" vs \"",
              "        & UNICHAR ( 10 ),",
              "    'Team'[Team]",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "1fa93af1-74a3-4be5-9154-208ec4467509",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Toss Result",
            "expression": [
              "",
              "VAR _TossWinner =",
              "    CALCULATE (",
              "        MAXX ( 'Team Players', RELATED ( 'Team'[Team] ) ),",
              "        USERELATIONSHIP ( 'Team Players'[toss_winner_id], 'Team'[team_id] )",
              "    )",
              "RETURN",
              "    IF (",
              "        NOT ISBLANK ( _TossWinner ),",
              "        _TossWinner & \" won the toss and elected to \"",
              "            & MAX ( Match[Toss Decision] )",
              "    )"
            ],
            "isHidden": true,
            "lineageTag": "b9b86330-0df5-4d80-b889-cbba7b01b553",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Man of the Match",
            "expression": [
              "",
              "CALCULATE (",
              "    MAXX ( 'Team Players', RELATED ( 'Player'[Player Name] ) ),",
              "    USERELATIONSHIP ( 'Team Players'[player_of_match_id], Player[player_id] )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "b4cf0dfd-015d-44a4-89a3-3f0a95e536e1",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          },
          {
            "name": "Player Teams",
            "expression": [
              "",
              "VAR _TeamsPlayed =",
              "    ADDCOLUMNS ( SUMMARIZE ( 'Team Players', 'Team'[Team] ), \"@Matches\", [Match #] )",
              "RETURN",
              "    CONCATENATEX (",
              "        _TeamsPlayed,",
              "        'Team'[Team] & \" (\" & [@Matches] & \")\",",
              "        \", \",",
              "        [@Matches], DESC",
              "    )"
            ],
            "isHidden": true,
            "lineageTag": "66f98e49-2292-4c21-86ee-21441b779a5e",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_MEASURES\",\"INTEGER_FORMATTING\"]}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "IsTableInBiModel",
            "value": "True"
          }
        ]
      },
      {
        "name": "Team",
        "lineageTag": "0d20bff5-3368-4e28-afa4-6d4cb6b85797",
        "sourceLineageTag": "[dbo].[t_dim_team]",
        "columns": [
          {
            "name": "team_id",
            "dataType": "int64",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "team_id",
            "formatString": "0",
            "sourceProviderType": "bigint",
            "lineageTag": "9f8113bd-7a5d-44cf-b6fb-8e47aa584411",
            "sourceLineageTag": "team_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Team",
            "dataType": "string",
            "sourceColumn": "team",
            "sourceProviderType": "varchar",
            "lineageTag": "8d684fb8-ca44-4ebc-aed1-1a0adb8da14e",
            "sourceLineageTag": "team",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Team",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "t_dim_team",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo"
            }
          }
        ],
        "annotations": [
          {
            "name": "IsTableInBiModel",
            "value": "True"
          }
        ]
      },
      {
        "name": "Team Match Filter",
        "isHidden": true,
        "lineageTag": "36a885fd-210d-45e0-9df4-af0665b79104",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "All Matches",
              "expression": [
                "IF (",
                "    ISFILTERED ( 'Team'[Team] ) || ISFILTERED ( 'Player'[Player Name] ),",
                "    VAR _MatchesOfTeam =",
                "        VALUES ( 'Team Players'[match_id] )",
                "    VAR _MatchesLineage =",
                "        TREATAS ( _MatchesOfTeam, 'Match'[match_id] )",
                "    RETURN",
                "        CALCULATE (",
                "            SELECTEDMEASURE (),",
                "            REMOVEFILTERS ( 'Team'[Team] ),",
                "            REMOVEFILTERS ( 'Player'[Player Name] ),",
                "            KEEPFILTERS ( _MatchesLineage )",
                "        ),",
                "    SELECTEDMEASURE ()",
                ")"
              ]
            },
            {
              "name": "Highest Score Match",
              "expression": [
                "VAR _Matches =",
                "    CALCULATETABLE (",
                "        ADDCOLUMNS ( VALUES ( 'Match'[match_id] ), \"@HighestScore\", [Batter's Runs] ),",
                "        ALLSELECTED ()",
                "    )",
                "VAR _TopMatches =",
                "    TOPN ( 1, _Matches, [@HighestScore], DESC )",
                "RETURN",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        REMOVEFILTERS ( 'Team'[Team] ),",
                "        REMOVEFILTERS ( 'Player'[Player Name] ),",
                "        KEEPFILTERS ( _TopMatches )",
                "    )"
              ]
            },
            {
              "name": "Highest Wicket Match",
              "expression": [
                "VAR _Matches =",
                "    CALCULATETABLE (",
                "        ADDCOLUMNS ( VALUES ( 'Match'[match_id] ), \"@Wickets\", [Wickets #] ),",
                "        ALLSELECTED ()",
                "    )",
                "VAR _TopMatches =",
                "    TOPN ( 1, _Matches, [@Wickets], DESC )",
                "RETURN",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        REMOVEFILTERS ( 'Team'[Team] ),",
                "        REMOVEFILTERS ( 'Player'[Player Name] ),",
                "        KEEPFILTERS ( _TopMatches )",
                "    )"
              ]
            },
            {
              "name": "100s Matches",
              "expression": [
                "VAR _Matches =",
                "    CALCULATETABLE (",
                "        ADDCOLUMNS (",
                "            SUMMARIZE ( 'Deliveries', 'Match'[match_id], 'Deliveries'[batter_id] ),",
                "            \"@Runs\", [Batter's Runs]",
                "        ),",
                "        ALLSELECTED ()",
                "    )",
                "VAR _TopMatches =",
                "    FILTER ( _Matches, [@Runs] >= 100 )",
                "VAR _MatchIds =",
                "    SELECTCOLUMNS ( _TopMatches, 'Match'[match_id] )",
                "RETURN",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        REMOVEFILTERS ( 'Team'[Team] ),",
                "        REMOVEFILTERS ( 'Player'[Player Name] ),",
                "        KEEPFILTERS ( _MatchIds )",
                "    )"
              ]
            },
            {
              "name": "5 Wickets Matches",
              "expression": [
                "VAR _Matches =",
                "    CALCULATETABLE (",
                "        ADDCOLUMNS (",
                "            SUMMARIZE ( 'Deliveries', 'Match'[match_id], 'Deliveries'[bowler_id] ),",
                "            \"@Wickets\", [Wickets #]",
                "        ),",
                "        ALLSELECTED ()",
                "    )",
                "VAR _TopMatches =",
                "    FILTER ( _Matches, [@Wickets] >= 5 )",
                "VAR _MatchIds =",
                "    SELECTCOLUMNS ( _TopMatches, 'Match'[match_id] )",
                "RETURN",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        REMOVEFILTERS ( 'Team'[Team] ),",
                "        REMOVEFILTERS ( 'Player'[Player Name] ),",
                "        KEEPFILTERS ( _MatchIds )",
                "    )"
              ]
            },
            {
              "name": "Highest 6s Match",
              "expression": [
                "VAR _Matches =",
                "    CALCULATETABLE (",
                "        ADDCOLUMNS ( VALUES ( 'Match'[match_id] ), \"@Sixes\", [Sixes #] ),",
                "        ALLSELECTED ()",
                "    )",
                "VAR _TopMatches =",
                "    TOPN ( 1, _Matches, [@Sixes], DESC )",
                "RETURN",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        REMOVEFILTERS ( 'Team'[Team] ),",
                "        REMOVEFILTERS ( 'Player'[Player Name] ),",
                "        KEEPFILTERS ( _TopMatches )",
                "    )"
              ]
            },
            {
              "name": "Highest 4s Match",
              "expression": [
                "VAR _Matches =",
                "    CALCULATETABLE (",
                "        ADDCOLUMNS ( VALUES ( 'Match'[match_id] ), \"@Fours\", [Fours #] ),",
                "        ALLSELECTED ()",
                "    )",
                "VAR _TopMatches =",
                "    TOPN ( 1, _Matches, [@Fours], DESC )",
                "RETURN",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        REMOVEFILTERS ( 'Team'[Team] ),",
                "        REMOVEFILTERS ( 'Player'[Player Name] ),",
                "        KEEPFILTERS ( _TopMatches )",
                "    )"
              ]
            },
            {
              "name": "Highest Runs per Over Match",
              "expression": [
                "VAR _Matches =",
                "    CALCULATETABLE (",
                "        ADDCOLUMNS (",
                "            SUMMARIZE (",
                "                'Deliveries',",
                "                'Match'[match_id],",
                "                'Deliveries'[innings],",
                "                'Deliveries'[overs]",
                "            ),",
                "            \"@HighestScore\", [Overall Runs]",
                "        ),",
                "        ALLSELECTED ()",
                "    )",
                "VAR _TopMatches =",
                "    TOPN ( 1, _Matches, [@HighestScore], DESC )",
                "VAR _MatchIds =",
                "    SELECTCOLUMNS ( _TopMatches, 'Match'[match_id] )",
                "RETURN",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        REMOVEFILTERS ( 'Team'[Team] ),",
                "        REMOVEFILTERS ( 'Player'[Player Name] ),",
                "        KEEPFILTERS ( _MatchIds )",
                "    )"
              ]
            },
            {
              "name": "Highest Wickets per Over Match",
              "expression": [
                "VAR _Matches =",
                "    CALCULATETABLE (",
                "        ADDCOLUMNS (",
                "            SUMMARIZE (",
                "                'Deliveries',",
                "                'Match'[match_id],",
                "                'Deliveries'[innings],",
                "                'Deliveries'[overs]",
                "            ),",
                "            \"@Wickets\", [Wickets #]",
                "        ),",
                "        ALLSELECTED ()",
                "    )",
                "VAR _TopMatches =",
                "    TOPN ( 1, _Matches, [@Wickets], DESC )",
                "VAR _MatchIds =",
                "    SELECTCOLUMNS ( _TopMatches, 'Match'[match_id] )",
                "RETURN",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        REMOVEFILTERS ( 'Team'[Team] ),",
                "        REMOVEFILTERS ( 'Player'[Player Name] ),",
                "        KEEPFILTERS ( _MatchIds )",
                "    )"
              ]
            },
            {
              "name": "Tied Matches",
              "expression": [
                "VAR _MatchesOfTeam =",
                "    CALCULATETABLE ( VALUES ( 'Match'[match_id] ), 'Match'[Match Result] = \"tie\" )",
                "RETURN",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        REMOVEFILTERS ( 'Team'[Team] ),",
                "        REMOVEFILTERS ( 'Player'[Player Name] ),",
                "        KEEPFILTERS ( _MatchesOfTeam )",
                "    )"
              ]
            },
            {
              "name": "Enable Team Filter",
              "expression": [
                "IF (",
                "    ISFILTERED ( 'Team'[Team] ) && NOT ISINSCOPE ( 'Team'[Team] ),",
                "    IF ( NOT ISEMPTY ( 'Team Players' ), SELECTEDMEASURE () ),",
                "    SELECTEDMEASURE ()",
                ")"
              ]
            }
          ]
        },
        "columns": [
          {
            "name": "Team Match Filter Activator",
            "dataType": "string",
            "sourceColumn": "Name",
            "lineageTag": "0f22deed-7f5d-4bf4-b96e-ce659580d7dc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"UNNECESSARY_COLUMNS\"]}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Date",
        "lineageTag": "380d78ee-680d-4ef0-9562-7fcb2b739ad2",
        "sourceLineageTag": "[dbo].[t_dim_date]",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "date",
            "formatString": "dd-MMM-yyyy",
            "sourceProviderType": "date",
            "lineageTag": "3d97ba49-83cc-4a99-8883-598ebb761429",
            "sourceLineageTag": "date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "TabularEditor_MarkAsDateKey",
                "value": "1"
              },
              {
                "name": "BestPracticeAnalyzer_IgnoreRules",
                "value": "{\"RuleIDs\":[\"RELATIONSHIP_COLUMNS_SHOULD_BE_OF_INTEGER_DATA_TYPE\",\"DATECOLUMN_FORMATSTRING\"]}"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "year",
            "formatString": "0",
            "sourceProviderType": "int",
            "lineageTag": "6f88741f-c450-4f03-84e0-c8784f18968f",
            "sourceLineageTag": "year",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "quarter",
            "sourceProviderType": "varchar",
            "lineageTag": "c6accae7-0907-469e-ad73-e9458355be8b",
            "sourceLineageTag": "quarter",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "month_number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "month_number",
            "formatString": "0",
            "sourceProviderType": "int",
            "lineageTag": "48b322ee-97bb-4718-809b-0f220270ab65",
            "sourceLineageTag": "month_number",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "month",
            "sortByColumn": "month_number",
            "sourceProviderType": "varchar",
            "lineageTag": "363a548f-b992-4703-86e6-b0bf737f6018",
            "sourceLineageTag": "month",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "t_dim_date",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo"
            }
          }
        ],
        "annotations": [
          {
            "name": "IsTableInBiModel",
            "value": "True"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "f36bd119-e510-5cda-3f62-92006c4d3bac",
        "fromTable": "Team Players",
        "fromColumn": "team_id",
        "toTable": "Team",
        "toColumn": "team_id"
      },
      {
        "name": "5fbb0ef7-b010-73aa-79e7-92b79d6cb1f1",
        "fromTable": "Team Players",
        "fromColumn": "player_id",
        "toTable": "Player",
        "toColumn": "player_id"
      },
      {
        "name": "e970f436-4cb7-e1aa-ccd7-50530bfb8009",
        "fromTable": "Team Players",
        "fromColumn": "match_id",
        "toTable": "Match",
        "toColumn": "match_id"
      },
      {
        "name": "93d2718e-d03c-37f2-8af4-491f4003d3ed",
        "fromTable": "Deliveries",
        "fromColumn": "match_id",
        "toTable": "Match",
        "toColumn": "match_id"
      },
      {
        "name": "168fb4c0-56e3-44df-9ca7-b6992a29dd7a",
        "fromTable": "Deliveries",
        "fromColumn": "batter_id",
        "toTable": "Player",
        "toColumn": "player_id"
      },
      {
        "name": "724bc175-db19-481e-b332-89b9d8301461",
        "fromTable": "Deliveries",
        "fromColumn": "bowler_id",
        "toTable": "Player",
        "toColumn": "player_id",
        "isActive": false
      },
      {
        "name": "c3f0bcfc-f403-46b1-b0a0-53aa1f91686d",
        "fromTable": "Deliveries",
        "fromColumn": "fielder_id",
        "toTable": "Player",
        "toColumn": "player_id",
        "isActive": false,
        "annotations": [
          {
            "name": "BestPracticeAnalyzer_IgnoreRules",
            "value": "{\"RuleIDs\":[\"INACTIVE_RELATIONSHIPS_THAT_ARE_NEVER_ACTIVATED\"]}"
          }
        ]
      },
      {
        "name": "d0dfa01c-ce9e-42fa-bc0d-839e6ebb5a5f",
        "fromTable": "Deliveries",
        "fromColumn": "non_striker_id",
        "toTable": "Player",
        "toColumn": "player_id",
        "isActive": false
      },
      {
        "name": "23d28bae-0ea3-4d03-82c5-fd51b07dd261",
        "fromTable": "Deliveries",
        "fromColumn": "player_out_id",
        "toTable": "Player",
        "toColumn": "player_id",
        "isActive": false
      },
      {
        "name": "8b36b6e9-86f4-4924-838c-992c5628076a",
        "fromTable": "Deliveries",
        "fromColumn": "batting_team_id",
        "toTable": "Team",
        "toColumn": "team_id"
      },
      {
        "name": "5b90c227-27fb-433e-b96d-7103a15adbe9",
        "fromTable": "Deliveries",
        "fromColumn": "match_date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "0fba8210-5ea8-443f-99bc-3399ef17ba13",
        "fromTable": "Team Players",
        "fromColumn": "match_date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "c75d4d87-ced3-48dd-96dc-8ffb50f76b97",
        "fromTable": "Team Players",
        "fromColumn": "first_bat_id",
        "toTable": "Team",
        "toColumn": "team_id",
        "isActive": false,
        "annotations": [
          {
            "name": "BestPracticeAnalyzer_IgnoreRules",
            "value": "{\"RuleIDs\":[\"INACTIVE_RELATIONSHIPS_THAT_ARE_NEVER_ACTIVATED\"]}"
          }
        ]
      },
      {
        "name": "794dc3c7-035c-40b7-98e0-1c6b94180555",
        "fromTable": "Team Players",
        "fromColumn": "first_field_id",
        "toTable": "Team",
        "toColumn": "team_id",
        "isActive": false,
        "annotations": [
          {
            "name": "BestPracticeAnalyzer_IgnoreRules",
            "value": "{\"RuleIDs\":[\"INACTIVE_RELATIONSHIPS_THAT_ARE_NEVER_ACTIVATED\"]}"
          }
        ]
      },
      {
        "name": "319f625f-82d3-47b5-9c7e-492de593f1eb",
        "fromTable": "Team Players",
        "fromColumn": "match_winner_id",
        "toTable": "Team",
        "toColumn": "team_id",
        "isActive": false
      },
      {
        "name": "3659c662-ccb8-4d51-8f47-c4e64455fa76",
        "fromTable": "Team Players",
        "fromColumn": "player_of_match_id",
        "toTable": "Player",
        "toColumn": "player_id",
        "isActive": false
      },
      {
        "name": "03412e1e-4cc5-421e-8922-e9c1a994d840",
        "fromTable": "Team Players",
        "fromColumn": "toss_winner_id",
        "toTable": "Team",
        "toColumn": "team_id",
        "isActive": false
      },
      {
        "name": "b7bd6c12-cce0-4671-b2aa-89130095d92e",
        "fromTable": "Deliveries",
        "fromColumn": "bowling_team_id",
        "toTable": "Team",
        "toColumn": "team_id",
        "isActive": false,
        "annotations": [
          {
            "name": "BestPracticeAnalyzer_IgnoreRules",
            "value": "{\"RuleIDs\":[\"INACTIVE_RELATIONSHIPS_THAT_ARE_NEVER_ACTIVATED\"]}"
          }
        ]
      }
    ],
    "expressions": [
      {
        "name": "DatabaseQuery",
        "kind": "m",
        "expression": [
          "let",
          "    database = Sql.Database(\"Fabric SQL Connection String\", \"SQL Analytics Endpoint ID\")",
          "in",
          "    database"
        ],
        "lineageTag": "7d8df1da-ff61-4ab8-95bf-e33335b82716"
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.125.7166.6 (Main)"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Perspectives\",\"Relationships\",\"Roles\",\"Shared Expressions\",\"Tables\",\"Tables/Calculation Items\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Translations\"]}"
      },
      {
        "name": "BestPracticeAnalyzer_IgnoreRules",
        "value": "{\"RuleIDs\":[\"ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS\",\"OBJECTS_WITH_NO_DESCRIPTION\"]}"
      },
      {
        "name": "BestPracticeAnalyzer_ExternalRuleFiles",
        "value": "[\"https://raw.githubusercontent.com/microsoft/Analysis-Services/master/BestPracticeRules/BPARules.json\"]"
      }
    ]
  }
}